### ISSUE TITLE
Config sent to daemon has nonsensical defaults

### ISSUE THREAD

**Issue by ycohen-dev** [lbryio/lbry-android-sdk#8]
## The Issue
When a user chooses to participate in the data network in the android app,
the daemon is started with additional components including the peer protocol server
this component heavily dependent on blob management.
The blob management is crippled when the the "save blobs" option is turned off.

https://github.com/lbryio/lbry-android-sdk/blob/a7ee2cd4d0a0c12462e5187301588596aa4c901a/src/main/python/lbrynetservice.py#L89-L99

When the blob management is not allowed to save files - it is serving blobs from memory only.
Is this the intended behavior?

**Comment by akinwale** [comment]
@ycohen-dev The reason `save_blobs` is set to `False` by default is due to storage space limitations on mobile. We will be able to set this to `True` for the participation in the data network once the SDK implements proper storage space management settings.
